steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/royalwbiq-backend:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/royalwbiq-backend:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "beta",
        "run",
        "deploy",
        "royalwbiq-backend",
        "--image=gcr.io/$PROJECT_ID/royalwbiq-backend:$SHORT_SHA",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-secrets",
        "MONGO_DB_URI=royalwbiq-db-uri:latest,FIREBASE_SERVICE_ACCOUNT=royalwbiq-service-account:latest,
        OPENAI_API_KEY=royalwbiq-openai-api-key:latest,
        AZURE_API_KEY=royalwbiq-azure-api-key:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
